version: "3.9"

services:
  database: 
    image: postgres
    container_name: database_ignite
    restart: always
    ports: 
      - 6001:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: 

